language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

install:
  - go get github.com/stretchr/testify

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
